production:
  root_url:   "cabildo.production-site.org"
  billit:     "billit.production-site.org"
  popit:		  "popit.production-site.org"
  writeit:    "none"
  scout:      "none"
  analytics:  "none"

development:
  root_url:   "http://beta.votainteligente.cl/"
  billit:     "http://billit.ciudadanointeligente.org/bills/"
  popit:      "http://billit-demo.popit.mysociety.org/persons/"
  writeit:    "none"
  scout:      "none"
  analytics:  "none"

test:
  root_url:   "cabildo.test-site.org"
  billit:     "http://billit.ciudadanointeligente.org/bills/"
  popit:      "popit.test-site.org"
  writeit:    "none"
  scout:      "none"
  analytics:  "none"
