production:
  root_url:   ~
  billit:     ~
  popit_persons:  "my-popit-instance.popit.org/api/v0.1/persons/"
  popit_url: ~
  tables:     ~
  writeit:    ~
  scout:      ~
  analytics:  "UA-XXXXX-X"
  disqus_shortname:         ~
  parliaments-initial-date: "1990-03-01"

development:
  root_url:   ~
  billit:     ~
  popit_persons:  "my-popit-instance.popit.org/api/v0.1/persons/"
  popit_url: ~
  tables:     ~
  writeit:    ~
  scout:      ~
  analytics:  "UA-XXXXX-X"
  disqus_shortname:         ~
  parliaments-initial-date: "1990-03-01"

test:
  root_url:   ~
  billit:     "http://127.0.0.1.xip.io:3003/bills/"
  popit_persons:  "http://localhost:3002/api/persons/"
  popit_url: "billit-demo.popit.mysociety.org"
  tables:     "http://pmo.apidone.com/tables"
  writeit:    ~
  scout:      ~
  analytics:  "UA-XXXXX-X"
  disqus_shortname:     ~
  parliaments-initial-date: "1990-03-01"
